package me.falu.peepopractice.core.category.properties.preset;

public class CommandsPreset {
    public static final String[] ADVANCEMENT_GRANT_END_GAME = new String[] {
            "gamerule announceAdvancements false",
            "advancement grant @a only minecraft:end/dragon_breath",
            "advancement grant @a only minecraft:end/kill_dragon",
            "advancement grant @a only minecraft:end/dragon_egg",
            "advancement grant @a only minecraft:end/root",
            "advancement grant @a only minecraft:story/smelt_iron",
            "advancement grant @a only minecraft:story/mine_stone",
            "advancement grant @a only minecraft:story/iron_tools",
            "advancement grant @a only minecraft:story/follow_ender_eye",
            "advancement grant @a only minecraft:story/enter_the_nether",
            "advancement grant @a only minecraft:story/enter_the_end",
            "advancement grant @a only minecraft:story/root",
            "advancement grant @a only minecraft:story/obtain_armor",
            "advancement grant @a only minecraft:story/form_obsidian",
            "advancement grant @a only minecraft:story/lava_bucket",
            "advancement grant @a only minecraft:adventure/kill_a_mob",
            "advancement grant @a only minecraft:adventure/root",
            "advancement grant @a only minecraft:nether/charge_respawn_anchor",
            "advancement grant @a only minecraft:nether/root",
            "advancement grant @a only minecraft:nether/distract_piglin",
            "advancement grant @a only minecraft:nether/find_bastion",
            "advancement grant @a only minecraft:nether/find_fortress",
            "advancement grant @a only minecraft:nether/loot_bastion",
            "advancement grant @a only minecraft:nether/obtain_blaze_rod",
            "advancement grant @a only minecraft:nether/obtain_crying_obsidian",
            "advancement grant @a only minecraft:husbandry/root",
            "advancement grant @a only minecraft:adventure/adventuring_time",
            "advancement grant @a only minecraft:end/find_end_city",
            "advancement grant @a only minecraft:nether/use_lodestone",
            "advancement grant @a only minecraft:end/enter_end_gateway",
            "advancement grant @a only minecraft:end/levitate",
            "advancement grant @a only minecraft:nether/return_to_sender",
            "advancement grant @a only minecraft:nether/uneasy_alliance",
            "advancement grant @a only minecraft:nether/obtain_ancient_debris",
            "advancement grant @a only minecraft:nether/fast_travel",
            "advancement grant @a only minecraft:nether/brew_potion",
            "advancement grant @a only minecraft:nether/ride_strider",
            "advancement grant @a only minecraft:nether/explore_nether",
            "advancement grant @a only minecraft:husbandry/breed_an_animal",
            "advancement grant @a only minecraft:husbandry/tactical_fishing",
            "advancement grant @a only minecraft:husbandry/tame_an_animal",
            "advancement grant @a only minecraft:husbandry/plant_seed",
            "advancement grant @a only minecraft:husbandry/complete_catalogue",
            "advancement grant @a only minecraft:adventure/shoot_arrow",
            "advancement grant @a only minecraft:adventure/ol_betsy",
            "advancement grant @a only minecraft:adventure/throw_trident",
            "advancement grant @a only minecraft:adventure/very_very_frightening",
            "advancement grant @a only minecraft:story/cure_zombie_villager",
            "advancement grant @a only minecraft:story/enchant_item",
            "advancement grant @a only minecraft:story/upgrade_tools",
            "advancement grant @a only minecraft:husbandry/silk_touch_nest",
            "advancement grant @a only minecraft:husbandry/fishy_business",
            "advancement grant @a only minecraft:adventure/summon_iron_golem",
            "advancement grant @a only minecraft:nether/get_wither_skull",
            "advancement grant @a only minecraft:story/mine_diamond",
            "advancement grant @a only minecraft:end/elytra",
            "advancement grant @a only minecraft:story/shiny_gear",
            "advancement grant @a only minecraft:adventure/bullseye",
            "advancement grant @a only minecraft:adventure/sniper_duel",
            "advancement grant @a only minecraft:adventure/sleep_in_bed",
            "advancement grant @a only minecraft:adventure/two_birds_one_arrow",
            "advancement grant @a only minecraft:adventure/arbalistic",
            "advancement grant @a only minecraft:adventure/trade",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:cat",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:chicken",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:cow",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:donkey",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:fox",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:hoglin",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:horse",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:llama",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:mooshroom",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:mule",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:ocelot",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:panda",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:pig",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:rabbit",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:sheep",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:strider",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:turtle",
            "advancement grant @a only minecraft:husbandry/bred_all_animals minecraft:wolf",
            "advancement grant @a only minecraft:husbandry/balanced_diet apple",
            "advancement grant @a only minecraft:husbandry/balanced_diet baked_potato",
            "advancement grant @a only minecraft:husbandry/balanced_diet beef",
            "advancement grant @a only minecraft:husbandry/balanced_diet beetroot",
            "advancement grant @a only minecraft:husbandry/balanced_diet beetroot_soup",
            "advancement grant @a only minecraft:husbandry/balanced_diet bread",
            "advancement grant @a only minecraft:husbandry/balanced_diet carrot",
            "advancement grant @a only minecraft:husbandry/balanced_diet chicken",
            "advancement grant @a only minecraft:husbandry/balanced_diet chorus_fruit",
            "advancement grant @a only minecraft:husbandry/balanced_diet cod",
            "advancement grant @a only minecraft:husbandry/balanced_diet cooked_beef",
            "advancement grant @a only minecraft:husbandry/balanced_diet cooked_chicken",
            "advancement grant @a only minecraft:husbandry/balanced_diet cooked_cod",
            "advancement grant @a only minecraft:husbandry/balanced_diet cooked_mutton",
            "advancement grant @a only minecraft:husbandry/balanced_diet cooked_porkchop",
            "advancement grant @a only minecraft:husbandry/balanced_diet cooked_rabbit",
            "advancement grant @a only minecraft:husbandry/balanced_diet cooked_salmon",
            "advancement grant @a only minecraft:husbandry/balanced_diet cookie",
            "advancement grant @a only minecraft:husbandry/balanced_diet dried_kelp",
            "advancement grant @a only minecraft:husbandry/balanced_diet golden_apple",
            "advancement grant @a only minecraft:husbandry/balanced_diet golden_carrot",
            "advancement grant @a only minecraft:husbandry/balanced_diet melon_slice",
            "advancement grant @a only minecraft:husbandry/balanced_diet mushroom_stew",
            "advancement grant @a only minecraft:husbandry/balanced_diet mutton",
            "advancement grant @a only minecraft:husbandry/balanced_diet poisonous_potato",
            "advancement grant @a only minecraft:husbandry/balanced_diet porkchop",
            "advancement grant @a only minecraft:husbandry/balanced_diet potato",
            "advancement grant @a only minecraft:husbandry/balanced_diet pumpkin_pie",
            "advancement grant @a only minecraft:husbandry/balanced_diet rabbit",
            "advancement grant @a only minecraft:husbandry/balanced_diet rabbit_stew",
            "advancement grant @a only minecraft:husbandry/balanced_diet rotten_flesh",
            "advancement grant @a only minecraft:husbandry/balanced_diet salmon",
            "advancement grant @a only minecraft:husbandry/balanced_diet spider_eye",
            "advancement grant @a only minecraft:husbandry/balanced_diet sweet_berries",
            "advancement grant @a only minecraft:husbandry/balanced_diet tropical_fish",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:blaze",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:cave_spider",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:creeper",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:drowned",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:elder_guardian",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:ender_dragon",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:enderman",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:endermite",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:ghast",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:guardian",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:hoglin",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:husk",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:magma_cube",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:phantom",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:piglin",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:shulker",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:silverfish",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:skeleton",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:slime",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:spider",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:stray",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:wither_skeleton",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:zoglin",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:zombie",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:zombie_villager",
            "advancement grant @a only minecraft:adventure/kill_all_mobs minecraft:zombified_piglin",
            "gamerule announceAdvancements true"
    };
}
